### ISSUE TITLE
Does it support Advanced Data Protection?

### ISSUE THREAD

**Issue by mvanduijker** [mandarons/icloud-docker#122]
Is it supported and are there any implications when turned on using this software to sync your data?

https://support.apple.com/en-gb/guide/security/sec973254c5f/web

<img width="462" alt="image" src="https://user-images.githubusercontent.com/1771206/215988948-9eef5bdb-2ae6-4d42-bbcf-413ff2b74684.png">

**Comment by mandarons** [comment]
Haven't tried that yet. Give it a try and see what happens. :)

**Comment by mvanduijker** [comment]
haha crap, I hoped someone already tried ;)
Will give it a go when I have some spare time.

**Comment by DominoDrifter** [comment]
Nope, it doesn't work sadly. Would be great if this could be added though! Log output:

```
Loading config from /app/config.yaml ...
Loading config from /app/config.yaml ...
2023-02-04 14:51:49,566 :: INFO :: root :: sync.py :: 71 :: Syncing drive...
2023-02-04 14:51:50,125 :: ERROR :: icloudpy.base :: base.py :: 186 :: Missing PCS cookies from the request (423)
Traceback (most recent call last):
  File "/app/./src/main.py", line 7, in <module>
    sync.sync()
  File "/app/src/sync.py", line 72, in sync
    sync_drive.sync_drive(config=config, drive=api.drive)
  File "/app/src/sync_drive.py", line 304, in sync_drive
    items=drive.dir(),
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 234, in __getattr__
    return getattr(self.root, attr)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 229, in root
    self, self.get_node_data("FOLDER::com.apple.CloudDocs::root")
  File "/app/venv/lib/python3.10/site-packages/icloudpy/services/drive.py", line 34, in get_node_data
    request = self.session.post(
  File "/app/venv/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 158, in request
    self._raise_error(code, reason)
  File "/app/venv/lib/python3.10/site-packages/icloudpy/base.py", line 187, in _raise_error
    raise api_error
icloudpy.exceptions.ICloudPyAPIResponseException: Missing PCS cookies from the request (423)
```

**Comment by DominoDrifter** [comment]
Feature request raised in mandarons/icloudpy#20

**Comment by mvanduijker** [comment]
Thanks for checking @harveybolton
