### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by madmaxxx89** [mandarons/icloud-docker#266]
Hello, 
when I try to enter my password using the command “icloud --session-directory=/config/session_data --username=********@*****.***” I get the wrong password every time. I then cancel with Ctrl+C.
But if I try to log in directly to ICLOUD it works.
The Docker container has actually worked for months.
Unfortunately, I can't say what has changed.
Do others have the same problem?

`
File "/lsiopy/lib/python3.11/site-packages/icloudpy/utils.py", line 15, in get_password
    return get_password_from_keyring(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/icloudpy/utils.py", line 37, in get_password_from_keyring
    raise ICloudPyNoStoredPasswordAvailableException(
icloudpy.exceptions.ICloudPyNoStoredPasswordAvailableException: No iCloudPy password for **********@*****.** could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lsiopy/bin/icloud", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/icloudpy/cmdline.py", line 205, in main
    password = utils.get_password(
               ^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/icloudpy/utils.py", line 20, in get_password
    return getpass.getpass(f"Enter iCloud password for {username}: ")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 77, in unix_getpass
    passwd = _raw_input(prompt, stream, input=input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/getpass.py", line 146, in _raw_input
    line = input.readline()
           ^^^^^^^^^^^^^^^^
KeyboardInterrupt
`

**Comment by ayybe** [comment]
did apple just kill legacy auth?

**Comment by caplam** [comment]
Apple has changed the way authenticating works. I think all projects relying on third party auth are impacted.
see this: https://github.com/gcobb321/icloud3_v3/issues/341

**Comment by barcar** [comment]
It looks like there’s a potential fix upstream in https://github.com/mandarons/icloudpy/pull/49

**Comment by robdejonge** [comment]
@madmaxxx89 Can you, as the author, please edit the title of this post to be something descriptive?

**Comment by nicoodeimos** [comment]
I can confirm I have the same problem. My password gets rejected all the time.

**Comment by lorenzomorandini** [comment]
Hi, new version of icloudpy seems to fix it, can we upgrade it here too? Thanks!

**Comment by mandarons** [comment]
Hi Folks, please try upgrading to latest version.

**Comment by lorenzomorandini** [comment]
@mandarons I confirm that it works with the latest version, thanks!
