### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bytechanger** [mandarons/icloud-docker#267]
Hi,

I get this error on all family accounts, except for me.
An not all photos and drive files where synced!

Newest docker 1.20.1

Greets

```
2024-11-01 10:27:51,719 :: INFO :: root :: sync.py :: 82 :: Syncing drive...

2024-11-01 10:29:02,619 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:02,800 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:03,070 :: ERROR :: icloudpy.base :: base.py :: 186 :: ObjectNotFoundException: Could not find document (NOT_FOUND)

2024-11-01 10:29:03,335 :: ERROR :: icloudpy.base :: base.py :: 186 :: ObjectNotFoundException: Could not find document (NOT_FOUND)

2024-11-01 10:29:03,607 :: ERROR :: icloudpy.base :: base.py :: 186 :: ObjectNotFoundException: Could not find document (NOT_FOUND)

2024-11-01 10:29:03,763 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:03,885 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:04,017 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:04,162 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:04,285 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:04,545 :: ERROR :: icloudpy.base :: base.py :: 186 :: ObjectNotFoundException: Could not find document (NOT_FOUND)

2024-11-01 10:29:04,670 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:04,794 :: ERROR :: icloudpy.base :: base.py :: 186 :: Bad Request (400)

2024-11-01 10:29:07,677 :: INFO :: root :: sync.py :: 84 :: Drive synced
```

**Comment by Bytechanger** [comment]
On other child this error occurs:
```
2024-11-01 10:51:08,950 :: INFO :: root :: sync_photos.py :: 134 :: Downloading /icloud/photos/all/2024/10/c857XXX5-2XXf-4250-931b-54bea50f1038__original__QWF2WEovcXhXYVAzVXXXZxeUFvZjcvcWQ1VQ==.jpg ...

Traceback (most recent call last):

  File "/app/./src/main.py", line 7, in <module>

    sync.sync()

  File "/app/src/sync.py", line 90, in sync

    sync_photos.sync_photos(config=config, photos=api.photos)

  File "/app/src/sync_photos.py", line 258, in sync_photos

    sync_album(

  File "/app/src/sync_photos.py", line 179, in sync_album

    process_photo(photo, file_size, destination_path, files, folder_format)

  File "/app/src/sync_photos.py", line 149, in process_photo

    photo_path = generate_file_name(

                 ^^^^^^^^^^^^^^^^^^^

  File "/app/src/sync_photos.py", line 77, in generate_file_name

    filename = photo.filename

               ^^^^^^^^^^^^^^

  File "/lsiopy/lib/python3.11/site-packages/icloudpy/services/photos.py", line 663, in filename

    return base64.b64decode(

           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/base64.py", line 88, in b64decode

    return binascii.a2b_base64(s, strict_mode=validate)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

binascii.Error: Incorrect padding

s6-rc: warning: unable to start service svc-icd: command exited 1
```

**Comment by Bytechanger** [comment]
And on another account I get Bad username or password for ....

Since update to iOS 18.1

**Comment by robdejonge** [comment]
Can you please edit the title of this post to be something descriptive?

**Comment by mandarons** [comment]
Please try version 1.20.2.

**Comment by robdejonge** [comment]
I'm still getting the `Bad username or password` error

**Comment by mandarons** [comment]
This should be resolved in version 1.22.0 or newer. We are no longer using s6-overlay.
