### ISSUE TITLE
[BUG] KeyError: 'medium' in photo_exists

### ISSUE THREAD

**Issue by jeff47** [mandarons/icloud-docker#50]
**Describe the bug**
An error occurs during the process_photo routine.  Other files seem to download fine.

```
2022-01-24T23:39:33.858349778Z Traceback (most recent call last):
2022-01-24T23:39:33.858359179Z   File "/app/./src/main.py", line 6, in <module>
2022-01-24T23:39:33.858424680Z     sync.sync()
2022-01-24T23:39:33.858433902Z   File "/app/src/sync.py", line 25, in sync
2022-01-24T23:39:33.858492048Z     sync_photos.sync_photos(
2022-01-24T23:39:33.858503176Z   File "/app/src/sync_photos.py", line 83, in sync_photos
2022-01-24T23:39:33.858555230Z     sync_album(
2022-01-24T23:39:33.858562917Z   File "/app/src/sync_photos.py", line 68, in sync_album
2022-01-24T23:39:33.858621337Z     process_photo(photo, file_size, destination_path, verbose)
2022-01-24T23:39:33.858634493Z   File "/app/src/sync_photos.py", line 56, in process_photo
2022-01-24T23:39:33.858673947Z     if photo_exists(photo, file_size, photo_path, verbose=verbose):
2022-01-24T23:39:33.858684174Z   File "/app/src/sync_photos.py", line 27, in photo_exists
2022-01-24T23:39:33.858743616Z     remote_size = int(photo.versions[file_size]["size"])
2022-01-24T23:39:33.858753439Z KeyError: 'medium'
```

**Configuration**
Standard config, with file_sizes set to original & medium.

**Comment by mandarons** [comment]
Interesting. It looks like for some of your photos, `file_size` medium does not exist. I will fix it by skipping the missing file sizes.

**Comment by jeff47** [comment]
Yes - I wonder if this caused the issue I mentioned on reddit, where not all my photos were downloading.  If it hit this error, would it stop iterating and interrupt the download process for the remaining photos?  Possibly needs a more graceful response if this situation is encountered.

**Comment by mandarons** [comment]
Yeah, I suspect that's the reason.

**Comment by mandarons** [comment]
Please try with docker tag 'main' and see if that fixes the issue.
