### ISSUE TITLE
Error when syncing

### ISSUE THREAD

**Issue by brodybuster** [mandarons/icloud-docker#57]
This looks like a promising project that I would really like to get working. I installed per the readme. Getting the following error when attempting to sync:

Traceback (most recent call last):
  File "/app/./src/main.py", line 6, in <module>
    sync.sync()
  File "/app/src/sync.py", line 28, in sync
    config=config, photos=api.photos, verbose=verbose
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 578, in photos
    self._photos = PhotosService(service_root, self.session, self.params)
  File "/app/venv/lib/python3.9/site-packages/icloudpy/services/photos.py", line 147, in __init__
    request = self.session.post(
  File "/app/venv/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 158, in request
    self._raise_error(code, reason)
  File "/app/venv/lib/python3.9/site-packages/icloudpy/base.py", line 176, in _raise_error
    raise api_error
icloudpy.exceptions.ICloudPyServiceNotActivatedException: Please log into https://icloud.com/ to manually finish setting up your iCloud service (ZONE_NOT_FOUND)

Any help would be greatly appreciated!

**Comment by mandarons** [comment]
This seems like your iCloud settings issue. Per https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/107#issuecomment-534162296, it looks like you need to enable auto-upload option in iPhone (Settings > Your Name > iCloud > Photos > iCloud Photos set to ON). Confirm that it is working by taking a photo from iPhone and seeing it on iCloud.com.

**Comment by brodybuster** [comment]
All my devices have auto-upload (iCloud sync) enabled, so I don't think that is the issue.

**Comment by mandarons** [comment]
It's going to be challenging to fix this as I cannot reproduce it. I will still try.

Which version of iOS are you using?

**Comment by mandarons** [comment]
It looks like the error is possibly because your iCloud photos library didn't finish indexing. Try again after some time (few hours, may be).
